### PR TITLE
Release 1.4.6

### PR DESCRIPTION
**Pull request by phbelitz**
### Docs
- adjust public keys in READMEs to DockerHub Repo [(#102)](https://github.com/sse-secure-systems/connaisseur/pull/102)

### Fix
- adjust public keys in READMEs to DockerHub Repo [(#102)](https://github.com/sse-secure-systems/connaisseur/pull/102)
- Never use non-validated data for validation [(#89)](https://github.com/sse-secure-systems/connaisseur/pull/89)

### Feat
- Enable Per-Namespace verification [(#100)](https://github.com/sse-secure-systems/connaisseur/pull/100)

### Refactor
- Reduce complexity of 'process_chain_of_trust' [(#89)](https://github.com/sse-secure-systems/connaisseur/pull/89)

### Hotfix
- updated pylint [(#97)](https://github.com/sse-secure-systems/connaisseur/pull/97)

### Ci
- updated pylint [(#97)](https://github.com/sse-secure-systems/connaisseur/pull/97)

### CODE REVIEW

**Comment by phbelitz** [comment]
do I have to create a new release...? or do we just merge this into master?

**Comment by peterthomassen** [comment]
no release I'd say, as the linter only belongs to the dev / build chain, right?

**Comment by phbelitz** [comment]
yea but we still need it in master, as the nighlty builds will fail

**Comment by phbelitz** [comment]
gnar, but if we merge this, the commit won't have the "v1.4.5" tag and our version match pipeline will fail.

**Comment by Starkteetje** [comment]
It changes code that runs when used -> new release

**Review by Starkteetje — APPROVED** [review]

**Pull request merged**
